# .github/workflows/check-requirements.yml
name: Check Requirements
on:
  push:
    branches: [ main ]
jobs:
  check-requirements:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Linux requirements
      run: pip install -r requirements-linux.txt
    - name: Check for outdated packages
      run: pip list --outdated